# Generated by Django 4.2.5 on 2023-09-21 10:48

import brand.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faName', models.CharField(max_length=100, verbose_name='Persian Name')),
                ('enName', models.CharField(max_length=100, verbose_name='English Name')),
                ('briefExplamations', models.TextField()),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Description About Brand')),
                ('country', models.CharField(max_length=100)),
                ('logo1th', models.ImageField(upload_to=brand.models.BrandLogoImagePath)),
                ('logoBlured', models.ImageField(blank=True, null=True, upload_to=brand.models.BrandLogoBluredImagePath)),
                ('logo2th', models.ImageField(blank=True, null=True, upload_to=brand.models.BrandLogoSecImagePath)),
                ('logoSlider', models.ImageField(blank=True, null=True, upload_to=brand.models.BrandLogoSliderImagePath)),
                ('numberOfProducts', models.IntegerField(default=0)),
                ('numberOfEmployees', models.IntegerField(default=0)),
                ('foundedDate', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
