# Generated by Django 4.2.5 on 2023-09-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='briefExplamations',
            new_name='brief_explamations',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='enName',
            new_name='en_name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='faName',
            new_name='fa_name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='foundedDate',
            new_name='founded_date',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='logo1th',
            new_name='logo_1th',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='logo2th',
            new_name='logo_2th',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='logoBlured',
            new_name='logo_blured',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='logoSlider',
            new_name='logo_slider',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='numberOfEmployees',
            new_name='number_of_employees',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='numberOfProducts',
            new_name='number_of_products',
        ),
    ]
