# Generated by Django 4.2.5 on 2023-09-19 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=12, unique=True)),
                ('joined_at', models.CharField(max_length=30)),
                ('modified_at', models.CharField(blank=True, max_length=30, null=True)),
                ('lastlogin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=4)),
                ('gender', models.IntegerField(choices=[(0, 'Null'), (1, 'Male'), (2, 'Female'), (3, 'Whatyouneed')], default=0)),
                ('birthday_date', models.CharField(max_length=30)),
                ('complited_at', models.CharField(max_length=30)),
                ('AdminLogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.adminlogin')),
            ],
        ),
    ]
