# Generated by Django 4.2.5 on 2023-10-01 18:04

import category.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('vector', models.ImageField(upload_to=category.models.CategoryVectorImagePath)),
                ('position', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
                ('url', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategorySubset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('vector', models.ImageField(upload_to=category.models.SubsetVectorImagePath)),
                ('subset_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
                ('url', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('ProductCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.productcategory')),
            ],
        ),
    ]
