# Generated by Django 4.2.5 on 2023-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorysubset',
            name='ref_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
