# Generated by Django 4.2.5 on 2023-09-19 12:12

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import jdatetime
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminstrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=50)),
                ('numberOfUsed', models.IntegerField(default=1)),
                ('numbOfClicked', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=blog.models.BlogPosterPath, verbose_name='Blog Poster')),
                ('title', models.CharField(max_length=150, verbose_name='Title of Post')),
                ('description', models.CharField(max_length=10000, verbose_name='Description of Post')),
                ('tags', models.CharField(max_length=500, verbose_name='Tags of Post')),
                ('article_text', ckeditor.fields.RichTextField()),
                ('J_addition_datetime', models.CharField(default=jdatetime.date.today, max_length=15)),
                ('J_editition_datetime', models.CharField(default=jdatetime.date.today, max_length=15)),
                ('day', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=150)),
                ('special_blog', models.BooleanField(default=False, verbose_name='its special ?')),
                ('active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.adminlogin')),
                ('author_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator.admininfo')),
            ],
        ),
    ]
