# Generated by Django 4.2.5 on 2023-09-20 14:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='second_poster',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.BlogPosterPath, verbose_name='Second Blog Poster'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.BlogPosterPath, verbose_name='First Blog Poster'),
        ),
    ]
