# Generated by Django 4.2.5 on 2023-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_second_poster_alter_blog_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readingtime',
            field=models.CharField(default='ذکر نشده است .', max_length=255),
        ),
    ]
