# Generated by Django 4.2.5 on 2023-09-21 06:57

from django.db import migrations, models
import schneiderplus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=schneiderplus.models.sliderPosterPath)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
