# Generated by Django 4.2.5 on 2023-09-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schneiderplus', '0002_slider_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_phone_1th', models.IntegerField(blank=True, null=True)),
                ('tel_phone_2th', models.IntegerField(blank=True, null=True)),
                ('mobile_phone_1th', models.IntegerField(blank=True, null=True)),
                ('mobile_phone_2th', models.IntegerField(blank=True, null=True)),
                ('telegram_phone', models.IntegerField(blank=True, null=True)),
                ('whatsapp_phone', models.IntegerField(blank=True, null=True)),
                ('ita_phone', models.IntegerField(blank=True, null=True)),
                ('rubika_phone', models.IntegerField(blank=True, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1th', models.CharField(blank=True, max_length=255, null=True)),
                ('address_2th', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('week', models.CharField(blank=True, max_length=255, null=True, verbose_name='Working hours on weeks')),
                ('weekend', models.CharField(blank=True, max_length=255, null=True, verbose_name='Working hours on weekends')),
            ],
        ),
    ]
