# Generated by Django 4.2.5 on 2023-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schneiderplus', '0003_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='ita_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='mobile_phone_1th',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='mobile_phone_2th',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='rubika_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='tel_phone_1th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='this number for call to you about buying product'),
        ),
        migrations.AlterField(
            model_name='support',
            name='tel_phone_2th',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='telegram_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
